framework:
    asset_mapper:
        # On commente ou on enlève la ligne qui cherche le dossier assets/
        paths:
            # - assets/ 
        missing_import_mode: warn # On passe en "warn" pour éviter les crashs

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn